In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression

In [ ]:
class Linear_Regression():

   def __init__( self,learning_rate, no_of_iterations) :
        self.learning_rate = learning_rate
        self.no_of_iterations = no_of_iterations

    # fit function to train the model
   def fit( self, X, Y ) :
        # no_of_training_examples, no_of_features
        self.m, self.n = X.shape
        # initiating the weight and bias
        self.w = np.zeros( self.n )
        self.b = 0
        self.X = X
        self.Y = Y
        # implementing Gradient Descent for Optimization
        for i in range( self.no_of_iterations ) :
            self.update_weights()

    # function to update weights in gradient descent
   def update_weights( self ) :
        Y_prediction = self.predict( self.X )
        # calculate gradients
        dw = - ( 2 * ( self.X.T ).dot( self.Y - Y_prediction )  ) / self.m
        db = - 2 * np.sum( self.Y - Y_prediction ) / self.m
        # updating the weights
        self.w = self.w - self.learning_rate * dw
        self.b = self.b - self.learning_rate * db

        # Line function for prediction:
   def predict( self, X ) :
        return X.dot( self.w ) + self.b

In [ ]:
jalgaon=pd.read_csv("/content/jalgaon_crop.csv")
jalgaon

,Unnamed: 0,Dist Code,Year,State Code,State Name,Dist Name,RICE HARVEST PRICE (Rs per Quintal),PADDY HARVEST PRICE (Rs per Quintal),WHEAT HARVEST PRICE (Rs per Quintal),SORGHUM HARVEST PRICE (Rs per Quintal),...,SUGARCANE YIELD (Kg per ha),COTTON AREA (1000 ha),COTTON PRODUCTION (1000 tons),COTTON YIELD (Kg per ha),FRUITS AREA (1000 ha),VEGETABLES AREA (1000 ha),FRUITS AND VEGETABLES AREA (1000 ha),POTATOES AREA (1000 ha),ONION AREA (1000 ha),FODDER AREA (1000 ha)
0,2143,101,1990,7,Maharashtra,Jalgaon,0.0,0.0,308.0,188.0,...,8094.87,189.3,32.45,171.42,50.60,4.30,54.90,0.00,2.60,6.1
1,2144,101,1991,7,Maharashtra,Jalgaon,0.0,0.0,431.0,352.0,...,7153.02,204.0,18.97,92.99,47.20,3.50,50.70,0.00,1.60,2.0
2,2145,101,1992,7,Maharashtra,Jalgaon,0.0,0.0,379.0,288.0,...,8058.59,175.1,34.26,195.66,46.90,4.00,50.90,0.00,2.10,2.2
3,2146,101,1993,7,Maharashtra,Jalgaon,0.0,0.0,403.0,335.0,...,8709.80,210.1,43.40,206.57,48.00,3.70,51.70,0.00,1.60,1.8
4,2147,101,1994,7,Maharashtra,Jalgaon,0.0,403.0,439.0,311.0,...,8563.24,263.3,58.74,223.09,49.00,3.50,52.50,0.00,1.60,2.3
5,2148,101,1995,7,Maharashtra,Jalgaon,0.0,403.0,439.0,311.0,...,8477.97,277.9,53.43,192.26,48.20,3.70,51.90,0.00,1.70,2.5
6,2149,101,1996,7,Maharashtra,Jalgaon,0.0,480.0,483.0,381.0,...,8293.71,289.9,76.08,262.44,46.10,4.10,50.20,0.00,1.60,3.0
7,2150,101,1997,7,Maharashtra,Jalgaon,0.0,547.0,555.0,434.0,...,5273.13,287.8,53.24,184.99,46.10,4.40,50.50,0.00,1.70,3.1
8,2151,101,1998,7,Maharashtra,Jalgaon,0.0,541.0,574.0,441.0,...,9572.90,371.9,83.22,223.77,31.30,4.90,12.50,0.00,2.20,2.3
9,2152,101,1999,7,Maharashtra,Jalgaon,0.0,576.0,610.0,517.0,...,9271.13,332.6,79.49,239.00,39.90,6.50,46.40,0.00,3.50,4.7
10,2153,101,2000,7,Maharashtra,Jalgaon,0.0,611.0,626.0,520.0,...,8299.31,411.5,47.79,116.14,43.90,1.60,45.50,0.00,1.60,5.4
11,2154,101,2001,7,Maharashtra,Jalgaon,0.0,627.0,678.0,514.0,...,7462.22,403.0,85.83,212.98,38.30,1.00,39.30,0.00,1.00,5.6
12,2155,101,2002,7,Maharashtra,Jalgaon,0.0,603.0,660.0,506.0,...,7125.00,384.0,79.59,207.27,37.20,3.70,40.90,0.00,3.70,5.6
13,2156,101,2003,7,Maharashtra,Jalgaon,0.0,590.0,635.0,511.0,...,3383.85,383.6,87.52,228.15,37.90,5.30,43.20,0.00,5.30,0.0
14,2157,101,2004,7,Maharashtra,Jalgaon,0.0,591.0,608.0,533.0,...,6191.95,396.1,104.82,264.63,34.50,4.10,38.60,0.00,4.11,0.0
15,2158,101,2005,7,Maharashtra,Jalgaon,0.0,788.0,707.0,531.0,...,6464.71,393.4,102.71,261.08,44.10,2.40,46.50,0.00,2.24,0.0
16,2159,101,2006,7,Maharashtra,Jalgaon,0.0,780.0,780.0,616.0,...,6587.23,420.5,136.71,325.11,0.00,0.00,0.00,0.00,3.98,0.0
17,2160,101,2007,7,Maharashtra,Jalgaon,0.0,775.0,778.0,613.0,...,6644.64,416.0,161.25,387.62,0.00,0.00,0.00,0.00,6.85,0.0
18,2161,101,2008,7,Maharashtra,Jalgaon,0.0,650.0,1094.0,891.0,...,6536.75,434.6,132.62,305.15,0.00,0.00,0.00,0.00,0.00,0.0
19,2162,101,2009,7,Maharashtra,Jalgaon,0.0,825.0,1191.0,849.0,...,7035.42,413.6,116.46,281.58,0.00,0.00,0.00,0.00,0.00,0.0
20,2163,101,2010,7,Maharashtra,Jalgaon,0.0,1023.0,1308.0,981.0,...,7830.36,509.7,186.50,365.90,0.00,0.00,0.00,0.00,0.00,0.0
21,2164,101,2011,7,Maharashtra,Jalgaon,0.0,1000.0,1204.0,1542.0,...,7321.43,548.6,176.87,322.40,47.83,4.86,52.69,0.03,2.92,0.0
22,2165,101,2012,7,Maharashtra,Jalgaon,0.0,881.0,1355.0,1386.0,...,6900.91,558.8,145.06,259.59,38.55,12.24,50.79,0.00,9.27,0.0
23,2166,101,2013,7,Maharashtra,Jalgaon,0.0,0.0,1600.0,1293.0,...,7548.72,558.8,270.72,484.47,0.00,0.00,0.00,0.00,0.00,0.0
24,2167,101,2014,7,Maharashtra,Jalgaon,0.0,0.0,1441.0,1388.0,...,7007.59,471.1,138.26,293.48,0.00,0.00,0.00,0.00,0.00,0.0
25,2168,101,2015,7,Maharashtra,Jalgaon,0.0,0.0,1506.0,1379.0,...,7766.00,461.6,109.06,236.27,0.00,0.00,0.00,0.00,0.00,0.0

In [ ]:
jalgaon.shape

(26, 134)

In [ ]:
jalgaon.isnull().sum()

Unnamed: 0                              0
Dist Code                               0
Year                                    0
State Code                              0
State Name                              0
                                       ..
VEGETABLES AREA (1000 ha)               0
FRUITS AND VEGETABLES AREA (1000 ha)    0
POTATOES AREA (1000 ha)                 0
ONION AREA (1000 ha)                    0
FODDER AREA (1000 ha)                   0
Length: 134, dtype: int64

In [ ]:
x =['JANUARY PERCIPITATION (Millimeters)','FEBRUARY PERCIPITATION (Millimeters)'	,'MARCH PERCIPITATION (Millimeters)'	,'APRIL PERCIPITATION (Millimeters)'	,'MAY PERCIPITATION (Millimeters)'	,'JUNE PERCIPITATION (Millimeters)'	,'JULY PERCIPITATION (Millimeters)'	,'AUGUST PERCIPITATION (Millimeters)'	,'SEPTEMBER PERCIPITATION (Millimeters)'	,'OCTOBER PERCIPITATION (Millimeters)'	,'NOVEMBER PERCIPITATION (Millimeters)'	,'DECEMBER PERCIPITATION (Millimeters)',	'JANUARY MINIMUM (Centigrate)'	,'FEBRUARY MINIMUM (Centigrate)'	,'MARCH MINIMUM (Centigrate)'	,'APRIL MINIMUM (Centigrate)'	,'MAY MINIMUM (Centigrate)'	,'JUNE MINIMUM (Centigrate)'	,'JULY MINIMUM (Centigrate)'	,'AUGUST MINIMUM (Centigrate)'	,'SEPTEMBER MINIMUM (Centigrate)'	,'OCTOBER MINIMUM (Centigrate)'	,'NOVEMBER MINIMUM (Centigrate)'	,'DECEMBER MINIMUM (Centigrate)'	,'JANUARY MAXIMUM (Centigrate)'	,'FEBRUARY MAXIMUM (Centigrate)'	,'MARCH MAXIMUM (Centigrate)'	,'APRIL MAXIMUM (Centigrate)'	,'MAY MAXIMUM (Centigrate)'	,'JUNE MAXIMUM (Centigrate)'	,'JULY MAXIMUM (Centigrate)'	,'AUGUST MAXIMUM (Centigrate)'	,'SEPTEMBER MAXIMUM (Centigrate)'	,'OCTOBER MAXIMUM (Centigrate)'	,'NOVEMBER MAXIMUM (Centigrate)'	,'DECEMBER MAXIMUM (Centigrate)','WHEAT AREA (1000 ha)'	,'WHEAT PRODUCTION (1000 tons)','WHEAT YIELD (Kg per ha)']
X=jalgaon[x]
Y = np.array(jalgaon['WHEAT HARVEST PRICE (Rs per Quintal)'])
X

,JANUARY PERCIPITATION (Millimeters),FEBRUARY PERCIPITATION (Millimeters),MARCH PERCIPITATION (Millimeters),APRIL PERCIPITATION (Millimeters),MAY PERCIPITATION (Millimeters),JUNE PERCIPITATION (Millimeters),JULY PERCIPITATION (Millimeters),AUGUST PERCIPITATION (Millimeters),SEPTEMBER PERCIPITATION (Millimeters),OCTOBER PERCIPITATION (Millimeters),...,JUNE MAXIMUM (Centigrate),JULY MAXIMUM (Centigrate),AUGUST MAXIMUM (Centigrate),SEPTEMBER MAXIMUM (Centigrate),OCTOBER MAXIMUM (Centigrate),NOVEMBER MAXIMUM (Centigrate),DECEMBER MAXIMUM (Centigrate),WHEAT AREA (1000 ha),WHEAT PRODUCTION (1000 tons),WHEAT YIELD (Kg per ha)
0,0.24,1.49,0.46,0.00,54.76,191.41,241.13,275.61,108.10,55.63,...,35.64,30.62,30.46,30.63,32.80,31.87,30.60,35.3,55.90,1583.57
1,0.45,0.60,1.02,4.61,2.30,154.13,201.93,94.55,22.44,0.81,...,37.02,31.50,30.44,31.64,34.26,31.99,30.29,32.3,33.90,1049.54
2,0.00,0.00,0.00,0.31,17.67,96.48,118.67,242.33,164.02,32.23,...,38.51,32.94,30.13,30.96,32.90,31.66,30.84,35.8,60.20,1681.56
3,0.00,0.74,7.78,0.04,2.68,118.21,257.13,127.21,200.65,71.50,...,38.15,31.39,31.07,30.53,33.18,31.57,30.30,31.7,65.40,2063.09
4,14.59,0.74,0.00,9.11,7.45,190.85,288.84,236.91,192.82,26.36,...,35.88,29.86,29.82,30.45,33.85,31.67,30.66,37.1,80.20,2161.73
5,14.77,0.02,14.98,2.44,10.94,82.64,337.48,88.76,189.71,36.58,...,39.37,31.98,31.72,31.59,34.09,32.50,32.17,31.1,45.30,1456.59
6,8.47,0.08,7.24,1.22,3.60,59.13,309.18,155.09,191.60,97.40,...,38.26,32.05,30.16,30.98,32.47,32.09,30.94,39.8,74.40,1869.35
7,9.96,0.00,0.01,7.94,3.27,141.66,151.44,221.28,72.72,19.26,...,36.42,31.46,30.84,31.05,33.84,32.44,29.09,31.9,42.20,1322.88
8,2.72,0.24,7.68,0.69,5.08,82.61,199.46,183.93,232.18,39.21,...,38.77,31.90,31.73,31.10,33.76,31.66,30.58,43.8,72.20,1648.40
9,0.00,4.28,0.00,0.00,25.04,158.58,145.86,93.29,236.34,97.02,...,36.09,31.48,30.71,30.71,33.30,32.43,30.93,46.9,88.30,1882.73
10,0.00,0.43,0.09,0.02,9.70,179.04,192.11,143.95,44.94,11.19,...,36.54,30.60,31.39,31.93,34.62,33.78,32.03,22.6,31.60,1398.23
11,7.05,0.00,4.52,2.96,13.12,191.00,102.76,117.83,27.19,40.49,...,36.13,31.23,30.69,31.74,32.66,31.62,31.21,23.8,39.30,1651.26
12,0.26,2.08,7.32,6.56,2.65,207.87,36.02,203.89,108.33,17.42,...,36.82,32.42,29.90,30.86,34.66,32.50,32.40,27.7,53.20,1920.58
13,0.02,2.26,1.18,0.20,2.82,146.94,188.89,135.57,147.71,8.93,...,37.43,31.49,31.05,30.71,33.03,33.72,31.56,33.0,61.50,1863.64
14,4.21,0.00,0.98,0.12,25.80,136.60,157.97,224.42,164.40,35.56,...,37.15,32.36,30.12,31.68,32.50,32.43,30.76,38.4,77.70,2023.44
15,10.32,0.38,13.32,3.68,4.28,107.82,267.23,190.99,245.70,28.71,...,39.27,31.85,30.68,30.89,32.71,30.97,29.52,36.2,66.80,1845.30
16,0.00,0.00,47.64,0.16,41.24,111.90,280.45,354.88,212.80,37.46,...,37.15,30.92,29.91,31.06,33.45,32.43,31.89,50.8,111.90,2202.76
17,0.77,0.30,0.27,6.30,12.85,127.83,276.02,216.85,150.26,0.32,...,37.30,31.75,30.67,31.44,32.78,32.56,31.61,52.6,137.70,2617.87
18,0.00,0.03,11.00,0.67,0.74,97.89,164.46,140.48,210.30,12.58,...,37.37,32.02,31.01,30.63,33.59,33.16,32.58,31.6,64.60,2044.30
19,0.31,0.00,6.96,0.03,32.44,98.98,266.57,134.79,92.55,57.83,...,39.39,31.51,31.86,32.90,33.03,31.48,31.73,50.9,109.98,2160.71
20,8.19,0.56,9.41,0.32,1.79,139.17,228.42,300.69,169.80,44.46,...,38.11,31.77,31.17,32.04,34.22,33.52,29.86,66.0,164.59,2493.79
21,0.00,0.79,1.69,8.64,4.00,177.15,200.58,233.60,172.24,17.82,...,37.66,31.37,30.94,31.31,34.84,33.71,31.96,25.9,60.23,2325.48
22,2.45,0.03,0.00,0.53,9.71,75.21,230.18,167.16,219.91,31.16,...,38.13,31.95,31.48,31.55,33.84,31.93,31.87,25.3,52.97,2093.68
23,7.21,2.12,7.48,6.09,3.53,283.79,336.77,170.18,152.23,73.99,...,36.20,31.04,30.66,31.73,33.57,31.88,30.91,25.3,64.80,2561.27
24,8.61,3.17,15.93,3.88,11.16,16.75,294.84,144.95,177.31,13.57,...,39.93,32.74,32.24,31.62,34.99,33.70,30.25,49.6,81.10,1635.08
25,23.92,0.54,35.07,9.35,6.86,194.09,212.31,186.59,155.30,12.35,...,38.10,33.83,32.81,32.13,35.35,34.46,31.78,42.3,63.50,1501.18

In [ ]:
from sklearn.model_selection import *

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.33,random_state=2)
ytest

array([1441.,  308.,  610., 1308.,  780.,  660.,  483.,  403.,  778.])

In [ ]:
ytest.shape

(9,)

In [ ]:
model=Linear_Regression(learning_rate=0.02,no_of_iterations=2000)
model.fit(xtrain,ytrain)

<ipython-input-104-eed0dab30e7a>:28: RuntimeWarning: invalid value encountered in double_scalars
  self.b = self.b - self.learning_rate * db

In [ ]:
print(model.b)
print(model.w[0])
xtest

nan
nan

,JANUARY PERCIPITATION (Millimeters),FEBRUARY PERCIPITATION (Millimeters),MARCH PERCIPITATION (Millimeters),APRIL PERCIPITATION (Millimeters),MAY PERCIPITATION (Millimeters),JUNE PERCIPITATION (Millimeters),JULY PERCIPITATION (Millimeters),AUGUST PERCIPITATION (Millimeters),SEPTEMBER PERCIPITATION (Millimeters),OCTOBER PERCIPITATION (Millimeters),...,JUNE MAXIMUM (Centigrate),JULY MAXIMUM (Centigrate),AUGUST MAXIMUM (Centigrate),SEPTEMBER MAXIMUM (Centigrate),OCTOBER MAXIMUM (Centigrate),NOVEMBER MAXIMUM (Centigrate),DECEMBER MAXIMUM (Centigrate),WHEAT AREA (1000 ha),WHEAT PRODUCTION (1000 tons),WHEAT YIELD (Kg per ha)
24,8.61,3.17,15.93,3.88,11.16,16.75,294.84,144.95,177.31,13.57,...,39.93,32.74,32.24,31.62,34.99,33.70,30.25,49.6,81.10,1635.08
0,0.24,1.49,0.46,0.00,54.76,191.41,241.13,275.61,108.10,55.63,...,35.64,30.62,30.46,30.63,32.80,31.87,30.60,35.3,55.90,1583.57
9,0.00,4.28,0.00,0.00,25.04,158.58,145.86,93.29,236.34,97.02,...,36.09,31.48,30.71,30.71,33.30,32.43,30.93,46.9,88.30,1882.73
20,8.19,0.56,9.41,0.32,1.79,139.17,228.42,300.69,169.80,44.46,...,38.11,31.77,31.17,32.04,34.22,33.52,29.86,66.0,164.59,2493.79
16,0.00,0.00,47.64,0.16,41.24,111.90,280.45,354.88,212.80,37.46,...,37.15,30.92,29.91,31.06,33.45,32.43,31.89,50.8,111.90,2202.76
12,0.26,2.08,7.32,6.56,2.65,207.87,36.02,203.89,108.33,17.42,...,36.82,32.42,29.90,30.86,34.66,32.50,32.40,27.7,53.20,1920.58
6,8.47,0.08,7.24,1.22,3.60,59.13,309.18,155.09,191.60,97.40,...,38.26,32.05,30.16,30.98,32.47,32.09,30.94,39.8,74.40,1869.35
3,0.00,0.74,7.78,0.04,2.68,118.21,257.13,127.21,200.65,71.50,...,38.15,31.39,31.07,30.53,33.18,31.57,30.30,31.7,65.40,2063.09
17,0.77,0.30,0.27,6.30,12.85,127.83,276.02,216.85,150.26,0.32,...,37.30,31.75,30.67,31.44,32.78,32.56,31.61,52.6,137.70,2617.87

In [ ]:
prediction=model.predict(xtest)
prediction

24   NaN
0    NaN
9    NaN
20   NaN
16   NaN
12   NaN
6    NaN
3    NaN
17   NaN
dtype: float64

In [ ]:
model=LinearRegression()
model.fit(xtrain,ytrain)
predicted=model.predict(xtest)
print(predicted)

[  919.24135188  -116.05251533 -2318.4780548   -478.68210376
  1539.4654461    610.94478591   255.22224612   581.76814019
  -255.23686306]

In [ ]:
ytest

array([1441.,  308.,  610., 1308.,  780.,  660.,  483.,  403.,  778.])